trigger:
  branches:
    include:
      - master

pool: MyAgent1

stages:
  - stage: deployBuild
    jobs:
      - job: buildJob
        steps:
          
          - task: NodeTool@0
            displayName: node_tool_installer
            inputs:
              versionSource: 'spec'
              versionSpec: '22.x'

          - task: Npm@1
            displayName: Npm install
            inputs:
                  command: 'install'
                  workingDir: '$(System.DefaultWorkingDirectory)'

            
          - task: Npm@1
            displayName: Npm run build
            inputs:
                 command: 'custom'
                 workingDir: '$(System.DefaultWorkingDirectory)'
                 customCommand: 'run build'

          - task: CopyFilesOverSSH@0
            displayName: copying artifacts to /tmp/app
            inputs:
              sshEndpoint: 'VM-Connection'
              sourceFolder: '$(System.DefaultWorkingDirectory)/dist'
              contents: '**'
              targetFolder: '/tmp/app'
              readyTimeout: '20000'

          - task: SSH@0
            displayName: deployReact
            inputs:
                sshEndpoint: 'VM-Connection'
                runOptions: 'commands'
                commands: 'sudo cp -r /tmp/app/* /var/www/html'
                readyTimeout: '20000'

          

            

          